const tagNameData = [
  { id: 1, name: 'Hash', category: 'algorithm' },
  { id: 2, name: 'BFS/DFS', category: 'algorithm' },
  { id: 3, name: 'DP', category: 'algorithm' },
  { id: 4, name: 'Tree', category: 'algorithm' },
  { id: 5, name: 'Graph', category: 'algorithm' },
  { id: 6, name: 'Sort', category: 'algorithm' },
  { id: 7, name: 'Stack/Queue', category: 'algorithm' },
  { id: 8, name: 'Heap', category: 'algorithm' },
  { id: 9, name: 'Greedy', category: 'algorithm' },
  { id: 10, name: 'BS', category: 'algorithm' },
  { id: 11, name: 'C', category: 'language' },
  { id: 12, name: 'C#', category: 'language' },
  { id: 13, name: 'C++', category: 'language' },
  { id: 14, name: 'Clojure', category: 'language' },
  { id: 15, name: 'Dart', category: 'language' },
  { id: 16, name: 'Go', category: 'language' },
  { id: 17, name: 'Java', category: 'language' },
  { id: 18, name: 'JavaScript', category: 'language' },
  { id: 19, name: 'Kotlin', category: 'language' },
  { id: 20, name: 'ObjectiveC', category: 'language' },
  { id: 21, name: 'PHP', category: 'language' },
  { id: 22, name: 'Python', category: 'language' },
  { id: 23, name: 'R', category: 'language' },
  { id: 24, name: 'Ruby', category: 'language' },
  { id: 25, name: 'Rust', category: 'language' },
  { id: 26, name: 'Scala', category: 'language' },
  { id: 27, name: 'SQL', category: 'language' },
  { id: 28, name: 'Swift', category: 'language' },
  { id: 29, name: 'TypeScript', category: 'language' },
  { id: 30, name: 'Programmers', category: 'platform' },
  { id: 31, name: 'LeetCode', category: 'platform' },
  { id: 32, name: 'Beakjoon', category: 'platform' },
  { id: 33, name: 'HackerRank', category: 'platform' },
  { id: 34, name: 'etc', category: 'platform' },
  { id: 35, name: '⭐️', category: 'difficulty' },
  { id: 36, name: '⭐️⭐️', category: 'difficulty' },
  { id: 37, name: '⭐️⭐️⭐️', category: 'difficulty' },
  { id: 38, name: '⭐️⭐️⭐️⭐️', category: 'difficulty' },
  { id: 39, name: '⭐️⭐️⭐️⭐️⭐️', category: 'difficulty' },
  { id: 40, name: '하', category: 'understanding' },
  { id: 41, name: '중', category: 'understanding' },
  { id: 42, name: '상', category: 'understanding' },
];

export default tagNameData;