export const LOW_UNDERSTANDING = 40;
export const MIDDLE_UNDERSTANDING = 41;
export const HIGH_UNDERSTANDING = 42;
export const UNDERSTANING_LIST = [LOW_UNDERSTANDING, MIDDLE_UNDERSTANDING, HIGH_UNDERSTANDING];